# Generated by Django 3.2.7 on 2021-09-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
