# Generated by Django 3.2.7 on 2021-09-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_udata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='udata',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
